language: r
cache: packages

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - xdg-utils 
      - libcairo2-dev 
      - libclang-dev
      - libcurl4-openssl-dev
      - libjpeg-dev 
      - libudunits2-dev
      - libnode-dev
      - libxml2-dev 
      - mesa-common-dev
      - qpdf
      - unixodbc
      - unixodbc-dev
      - libharfbuzz-dev 
      - libfribidi-dev 

r_packages:
  - devtools
  - comorbidity
  - pkgdown
r_github_packages:
  - ramses-antibiotics/snomedizer

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - R -e 'print("hello world")'
  - R -e 'devtools::check()'

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then
    R -e 'covr::codecov(type = "all", token = Sys.getenv("CODECOVETOKEN"))';
    fi;

before_deploy:
  - if [ "$TRAVIS_BRANCH" = "master" -o "$TRAVIS_BRANCH" = "develop" ] && [ "$TRAVIS_R_VERSION_STRING" = "release" ]; then 
    Rscript ./pkgdown/build.R; 
    fi;

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: jiEnSwu0xq4bk6mKLDIvTiERWIXe3xAjy9cyVhUmCQuHPTkRrk9PXcz36lyjtJWUTtBuX69aIrWLm1bpEpU7Oi16UZtb42ltp1HLHw86GjPld/HS9KbXrSkQ39u1Q/GHEragfDDB4UhXxSbOB2DWWEJ+xrq5J9WndBv3lWezs0NGYrP0iNQpPNSDq1jLw10GYpWLv2ugUapEQX18m386E35D+ZYF0y56KQ6ie4O6GoFvmR8ZdVX0IrSgZIa0qAB2+RY8QrUMr97afrrhL95ZvZCx1nP69wB6ogyxYc9NosvSERZzsUkmfY9B4V/3Ot9CH8iQN1CznAWJycb0eRqRj0s5OsH90QtMvtlVFPpoE3pcY5vajDa81JWf/CacfBaUSZINLVNXZBUl08yAaGs0h3nBuDh6tcT7fRJVzIFdJBx6LE1TGVFNKUQDVmrlxwha/sCy6bnPrKiE0WeOcZ8lhnxyIuWHqV6blfWif7eWijuEBIe/+JEYzt2TpqhJHb7V1ynxBxOjP8x5Ute1+EIfDU1pJzqqHhsdJ+epejg3NBgyyWedrI2hGt0/AmU0EICadxp1A4ieZHpOhwuTL9CiPYUZpAXcppoYPHqo0XUoRe9ACw9fo/dbfNTsGmgiHFWrj7kgm42k9rpjoREFDmmvCJqKdCXYqLLntvOFuBjiUNo=
  project: "ramses-antibiotics"
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING = release
