language: minimal

env:
  - RAMSESIMAGE="pdutey/ramses:R3.6.2" COMPOSE_FILE="travis/docker-compose.yml" CODECOVETOKEN=$CODECOVETOKEN
  - RAMSESIMAGE="pdutey/ramses:R4.0.2" COMPOSE_FILE="travis/docker-compose.yml" CODECOVETOKEN=$CODECOVETOKEN

services:
  - docker

before_install:
  - echo $BASH_VERSION
  - echo $PWD
  - docker-compose --version
  - docker-compose up --no-start
  - docker-compose start
  - docker-compose ps

script:
  - docker-compose exec -w /mnt/Ramses/ r Rscript -e 'devtools::check()'

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$RAMSESIMAGE" == "pdutey/ramses:R4.0.2" ]; then 
      docker-compose exec -w /mnt/Ramses/ r Rscript -e 'covr::codecov(type = "all", token = Sys.getenv("CODECOVETOKEN"))'
    fi
