language: r

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - xdg-utils 
      - libcairo2-dev 
      - libclang-dev
      - libcurl4-openssl-dev
      - libjpeg-dev 
      - libudunits2-dev
      - libnode-dev
      - libxml2-dev 
      - mesa-common-dev
      - qpdf
      - unixodbc
      - unixodbc-dev
      
r_github_packages:
  - ramses-antibiotics/snomedizer

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - R -e 'print("hello world")'
  - R -e 'devtools::check()'

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then
    R -e 'covr::codecov(type = "all", token = Sys.getenv("CODECOVETOKEN"))';
    fi;

