language: minimal

env:
  - RAMSESIMAGE="pdutey/ramses:R3.6.2" COMPOSE_FILE="travis/docker-compose.yml"
  - RAMSESIMAGE="pdutey/ramses:R4.0.2" COMPOSE_FILE="travis/docker-compose.yml"

services:
  - docker

before_install:
  - echo $BASH_VERSION
  - echo $PWD
  - docker-compose --version
  - docker-compose up --no-start
  - docker-compose start
  - docker-compose ps

script:
  - docker-compose exec -w /mnt/Ramses/ r Rscript -e 'devtools::check()'
  - | 
    if [ "$RAMSESIMAGE" == "pdutey/ramses:R3.6.2" ]; then 
      docker-compose exec -w /mnt/Ramses/ r Rscript -e "covr::codecov(type = "all", token = ${CODECOVETOKEN})"
    fi

after_deploy:
  - ls
